version: '3'

services: 
  web:
    stdin_open: true
    tty: true
    build: .
    command: > 
      python -u run.py
    environment: 
      PYTHONBUFFERED: 'false'
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    hostname: 'web'

  celery:
    build: .
    command: celery worker -A ez_script_center.celery_worker --loglevel=info
    env_file:
      - .env
    volumes: 
      - '.:/app'
    hostname: 'celery'
    links: 
      - 'web'
    user: 'nobody'
      
